galaxy_info:
  author: Nishant Parhi
  description: "Routing VPN using ansible"
  min_ansible_version: 1.7
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system

dependencies: []

